# Generated by Django 4.2.11 on 2024-04-10 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='ФИО')),
                ('institution', models.CharField(max_length=250, verbose_name='Наименование учебного заведения')),
                ('phone_number', models.CharField(max_length=12, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=150, verbose_name='E-mail')),
            ],
            options={
                'verbose_name': 'Участника',
                'verbose_name_plural': 'Участники',
            },
        ),
    ]
